### ISSUE TITLE
Fix on Xwayland

### ISSUE THREAD

**Issue by atx** [atx/wtype#1]
For whichever reason the dynamically generated keymap does not propagate to an application running under Xwayland. This is likely a bug somewhere in sway/wlroots/Xwayland.

**Comment by atx** [comment]
So, this seems to be a combination of X not accepting keycodes larger than 255 in its keymap and also all inputs getting merged together. Not sure if there is any reasonable fix at the moment.

**Comment by emersion** [comment]
Maybe related: https://github.com/swaywm/sway/issues/5461#issuecomment-872633821

**Comment by atx** [comment]
> Maybe related: [swaywm/sway#5461 (comment)](https://github.com/swaywm/sway/issues/5461#issuecomment-872633821)

Yup, that seems to do the trick. Thanks for noticing.

Leaving open for a while longer, since:
 
   * Not sure if just doing `include "default"` for the `xkb_compatibility` and `xkb_types` sections won't cause some unforeseen issues down the line
   * It makes `xkbcli interactive-x11` crash for some weird reason. Other applications I have tested seem to do fine though, so it may just be a bug in `xkbcli`

**Comment by emersion** [comment]
`xkbcli interactive-x11` exits because it checks for `keycode == 9`, which we use for the 3rd character. Fix: https://github.com/xkbcommon/libxkbcommon/pull/253
