### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by alecmev** [atx/wtype#13]
Thanks for making `wtype`! Could you cut a release, please? That would enable Arch maintainers to add it to the community repository, [allowing them to enable the recently-added Wayland support in `rofimoji`](https://bugs.archlinux.org/task/68159#comment193436).

**Comment by atx** [comment]
Finally got around to fixing the two pending PRs. Released v0.1.

**Comment by alecmev** [comment]
Thank you!

**Comment by atx** [comment]
Released v0.2, because I apparently [can't use git](https://github.com/atx/wtype/issues/14#issuecomment-716806125).
