### ISSUE TITLE
alt and shift modifiers are ignored

### ISSUE THREAD

**Issue by rafikdraoui** [atx/wtype#14]
I'm trying to send the keys `alt+left` with `wtype -M alt -P left -p left -m alt`, but it doesn't work for me. At first I thought it might be because `alt` seems to be mapped to the same key code as `altgr`: https://github.com/atx/wtype/blob/74071228dea4047157ae82960a2541ecc431e4a1/main.c#L118-L119
And since I use the `altgr-intl` variant of the us xkb layout "alt+left" would really mean "altgr+left".

But even when I try simpler things like `wtype -M alt c -m alt` or `wtype -M shift c -m shift`, it seems like the modifier keys are ignored (i.e. only `c` is emitted, instead of `alt+c` and `C`.)

It does work when I use the `ctrl` or `logo` modifiers though.

I'm wondering if I'm doing anything wrong, and just missing something obvious to come up with the right invocation to make it work!

Using `master` of `wtype` on `sway` v1.5.

**Comment by atx** [comment]
Modifiers not being sent at all fixed in d0e502d1aa6ef5a00840299076cdfd49417e1fbe (could have sworn that it used to work...). The Alt modifier added in 7979f7b374cc8c3189d174a8b97c27efe731fd9b.

**Comment by rafikdraoui** [comment]
@atx I can't find those commits in `master`. Perhaps they are in an unpublished branch?

**Comment by atx** [comment]
Oh sorry, forgot to push, should have noticed that github was not autolinking...

**Comment by rafikdraoui** [comment]
Great, thank you!
