### ISSUE TITLE
small inconsistencies?

### ISSUE THREAD

**Issue by tibequadorian** [atx/wtype#21]
https://github.com/atx/wtype/blob/fb8cb526470308d36b28c33620fcb74916f952e8/meson.build#L3 says version 0.0.1
https://github.com/atx/wtype/blob/fb8cb526470308d36b28c33620fcb74916f952e8/man/wtype.1#L2 says version 0.2

https://github.com/atx/wtype/blob/fb8cb526470308d36b28c33620fcb74916f952e8/meson.build#L19 sets language to cpp not c

**Comment by atx** [comment]
Fixed, thanks!
