### ISSUE TITLE
What are the supported desktop environments?

### ISSUE THREAD

**Issue by tom-james-watson** [atx/wtype#22]
When I try to run `wtype` on Pop!_OS 20.10 on Gnome I get:

```
Compositor does not support the virtual keyboard protocol
```

Is there a list of what desktop environments we should expect this to work on? What would be needed to get this working on gnome? Thanks!

**Comment by atx** [comment]
The compositor needs to support the `virtual-keyboard-unstable-v1` protocol. It looks like mutter (the Gnome compositor) does not implement this yet. I do not see an issue about this in their Gitlab repository, so it might be a good idea to ask there

Other than that, it should work on any wlroots-based compositor (provided the protocol support it gets properly initialized). Not sure about KDE.

One way to check is by running `wev -g` and looking for something like:
```
[02:     wl_registry] global: interface: 'zwp_virtual_keyboard_manager_v1', version: 1, name: 30
```
in its output.

**Comment by edvard-munch** [comment]
I wish that the Readme had the info about wtype not working on Gnome

**Comment by mmoya** [comment]
> The compositor needs to support the `virtual-keyboard-unstable-v1` protocol. It looks like mutter (the Gnome compositor) does not implement this yet. I do not see an issue about this in their Gitlab repository, so it might be a good idea to ask there

Someone already requested support for it in [mutter#1974](https://gitlab.gnome.org/GNOME/mutter/-/issues/1974). Upstream [said](https://gitlab.gnome.org/GNOME/mutter/-/issues/1974#note_1290897) it's unlikely this will be supported and recommended using [libei](https://gitlab.freedesktop.org/libinput/libei#libei) instead.

**Comment by edrex** [comment]
libei won't emulate virtual-{input,keyboard} backends: 

> GNOME is unlikely to ever use a Wayland protocol and wlroots is unlikely to ever use a DBus protocol

https://gitlab.freedesktop.org/libinput/libei/-/issues/2

I think that's a correct assessment: wlroots folks take a hard line against DBUS protocols in the stack, while GNOME relies on DBUS for integration. Meanwhile, users don't care what the protocol is, they just want it to work.

It seems like the best we can do for now is create a tool which implements both the wayland protocols backend and the portal-based one with auto-detection.

**Comment by shula** [comment]
the same error on KDE,  all systems updated today, 2024-11-18
wtype  0.4-2

so if it doesn't work on KDE, and not on GNOME, which are around 60% of the DE, what does it do  work with?
