### ISSUE TITLE
Document stdin input

### ISSUE THREAD

**Issue by sternenseemann** [atx/wtype#23]
This would be useful for using `wtype` for things like `passmenu` where you would automatically fake type in a stored password via `wtype` instead of copying it to the clipboard.

Currently it'd need to be passed via argv which means leaking it to the process list.

**Comment by atx** [comment]
This has been added in #11. It is not yet documented in the manpage though.

**Comment by sternenseemann** [comment]
Oh thanks, missed that!

**Comment by albsch** [comment]
When I execute `echo "hello" | wtype -`, I expect `hello` to be typed and be equivalent to `wtype hello`. Instead, using `stdin` results in an extra `RETURN` key to be used after the input ends, equivalent to `wtype hello -P RETURN`. Is this intended?
