### ISSUE TITLE
Unicode Chromium Ozone Wayland

### ISSUE THREAD

**Issue by SebastienWae** [atx/wtype#25]
Same as for application [running under xwayland](https://github.com/atx/wtype/issues/1), unicodes are not working on Chromium when running it with the [ozone](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/ozone_overview.md) wayland platform. Though for some reason it's working under the x11 platform.

`chromium --user-data-dir=/tmp --enable-features=UseOzonePlatform --ozone-platform=wayland` # not working
`chromium --user-data-dir=/tmp --enable-features=UseOzonePlatform --ozone-platform=x11` # working

**Comment by atx** [comment]
Indeed, chromium seems to have _opinions_ on what keysyms are valid. I have pushed a81540b7d4920566ad271236ca88befc0002b462, which seems to at least fix this on `ungoogled-chromium_91.0.4472.164-1.1`
