### ISSUE TITLE
Compositor does not support the virtual keyboard protocol

### ISSUE THREAD

**Issue by makley273** [atx/wtype#29]
Hello pals

I tried using it for gesture control. While testing it with example commands such as "wtype k" or other it always throws `Compositor does not support the virtual keyboard protocol`
So no commands are executed.

Installed on Manjaro 21 with Gnome 40 using Wayland
tested with wtype 0.3 (from aur) and 0.3 (from git, manually build)

**Comment by emersion** [comment]
GNOME doesn't support the virtual-keyboard protocol, required for wtype to work.

**Comment by atx** [comment]
Indeed

**Comment by v217** [comment]
Is there alternative software like `wtype` for gnome on wayland? Thanks!

**Comment by yhojann-cl** [comment]
> Is there alternative software like `wtype` for gnome on wayland? Thanks!

There is no way or alternatives, Gnome has poor keyboard support:

- https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2789
- https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2790

**Comment by neilbeukes** [comment]
This is also an issue on Plasma. Any solution for Plasma?

**Comment by ReRubis** [comment]
@neilbeukes 
I found that there is ydotool and xdotool that work on plasma wayland.
