### ISSUE TITLE
Incorrect greek characters

### ISSUE THREAD

**Issue by schauveau** [atx/wtype#32]
I noticed that wtype does not properly handle some characters of the greek plane (and probably others). 
Most of them are fine but a few are converted to a different UTF character. Here are a few examples
- 'π' (U+03C0 / UTF-8 0xCF 0x80 ) becomes 'Ā' (U+0100 / UTF-8 0xC4 0x80)  
- 'ο' (U+03BF / UTF-8 0xCE 0xBF ) becomes 'ŋ' (U+014B / UTF-8 0xC5 0x8B)

I tried multiple Wayland applications (foot, Firefox, emacs-pgtk, wev) so that does not seem to be related to the client.    

I used the following bash command to test individual characters in the terminal.

    (bash) c=$'\u03C0' ; echo "==> '$c'" ; echo "$c" | hexdump -C ;  wtype "$c" -k return -M ctrl d ; hexdump -C
    ==> 'π'
    00000000  cf 80 0a                                          |...| 
    00000003 
    Ā
    00000000  c4 80 0a                                          |...|
    00000003

System information:
- Debian testing
- Sway 1.6
- Locale: C.UTF-8
- Keymap: English (US)

**Comment by atx** [comment]
This has been fixed in 33b8942, but since I have not tagged a new release since then, it has not made its way to distributions. Fixed by releasing v0.4
