### ISSUE TITLE
Accept pipe for text input

### ISSUE THREAD

**Issue by fabien-michel** [atx/wtype#33]
I would like to send a password fetched from gnome-keyring to wtype. To avoid passing it by argument, it would be nice and more secure  to allow it being passed from a pipe.

Something like this is expected since I still need to send return key after the text:
`wtype -i -k return | echo "bidule"` with -i indicate to paste pipe result here

**Comment by atx** [comment]
This is actually already supported:
```
echo "bidule" | wtype - -k return
```

EDIT: Ah, right, the tagged version did not have the feature documented in the manpage. This is now fixed in v0.4
