### ISSUE TITLE
Compositor does not support the virtual keyboard protocol

### ISSUE THREAD

**Issue by Sadi58** [atx/wtype#34]
Having installed `wtype` under _KDE neon_ from https://packages.debian.org/sid/amd64/wtype/download, I'm trying to use `wtype` as a replacement for `xdotool` and `wmctrl` in a couple of my startup scripts, which launch an app and then minimize or close its window (in the absence such feature in app settings).
However, when I try to use a custom keyboard shortcut (e.g. _meta+m_) like `wtype -M logo m -m logo m` to minimize the current window, I get this message: `Compositor does not support the virtual keyboard protocol`
I wonder what this means, and if/how I can overcome it.

Also, I couldn't figure out how to enter _(Page) Down_ or _(Page) Up_.
And also I think it might be better to add `meta` and `super` for the key defined currently as `logo` and `win`.

**Comment by 1ncend1ary** [comment]
I second this. I'm on Arch GNOME Wayland, with `wtype` version `3.0` installed from AUR. 

Running `sudo wtype` results in:

```
error: XDG_RUNTIME_DIR not set in the environment.
Wayland connection failed
```

**Comment by atx** [comment]
Right, this is because Gnome does not support the virtual-keyboard protocol, nor does it plan to do so apparently.

The Gnome issue tracking this is [here](https://gitlab.gnome.org/GNOME/mutter/-/issues/1974), including some hints as to what the planned alternative is.

**Comment by Sadi58** [comment]
@atx Sorry, I forgot to mention that I use KDE neon. So this should not be Gnome-related?

**Comment by atx** [comment]
> @atx Sorry, I forgot to mention that I use KDE neon. So this should not be Gnome-related?

Ah, sorry, was focused too much on the second comment. Unfortunately the answer is the same here --- KWin does not yet support the virtual-keyboard protocol. Compared to Gnome, the KDE developers [seem undecided](https://invent.kde.org/plasma/kwin/-/issues/74#note_369963) whether they want to implement it or not.

**Comment by Sadi58** [comment]
@atx Thanks! I hope they implement it.
