### ISSUE TITLE
Pressing the enter key

### ISSUE THREAD

**Issue by UltraBlackLinux** [atx/wtype#49]
Hey there,
I've been wondering how you are supposed to use the enter key. It seemingly has no key name, and I can't press keycodes it seems.

How do you do this?
Thanks!

**Comment by NI57721** [comment]
Try return
```
$ wtype "echo -e \"foo" -P return "bar\"" -P return
$ echo -e "foo
bar"
foo
bar
```

**Comment by UltraBlackLinux** [comment]
oooh thank you so much, that works perfectly!

I feel like Return is quite a dated name for the Enter key but whatever
