### ISSUE TITLE
Wayland connection failed on KDE Plasma 5.27 and Arch Linux

### ISSUE THREAD

**Issue by demurgos** [atx/wtype#53]
I installed `wtype` from [the Arch package](https://archlinux.org/packages/extra/x86_64/wtype/). When I try to run it I get the following error:
```
$ wtype a
Compositor does not support the virtual keyboard protocol
```

Are there some missing dependencies that I should download/install/enable? I use Wayland on KDE Plasma 5.27 and Arch Linux.

**Comment by demurgos** [comment]
Closing: duplicate of https://github.com/atx/wtype/issues/45

**Comment by zararashigal** [comment]
> Closing: duplicate of [#45](https://github.com/atx/wtype/issues/45)

Then fix it.
