### ISSUE TITLE
wtype is crashing wayland windows

### ISSUE THREAD

**Issue by calbrecht** [atx/wtype#6]
There was an Alacritty issue, where an user demonstrated lag with the `xdotool` and i did test it with `wtype` on `sway`.

I found that i can reliably crash any wayland window by focusing it before wtyping to it.

`wtype $(seq 1 500)` reliably crashes kitty or alacritty on wayland.
`swaymsg '[app_id=firefox] focus' && wtype $(seq 1 500)` reliably crashes firefox.

`for i in $(seq 1 5000) ; do wtype $i ; done` within a terminal (Alacritty) and then changing the focus to a firefox window and trying to focus an input field, crashes firefox.

wtype should not crash other applications.

**Comment by curiositry** [comment]
wtype is also crashing Wayland windows for me (messing up keyboard input, it seems, at the very least). I am running Sway on Ubuntu 20.04

**Comment by atx** [comment]
Adding 2ms delay between sending the events seems to fix the issue from wtypes side.

It's still weird that some clients straight up crash when they get sent too many key events at once, but it looks like that is an issue with their handling of libwayland (or maybe with libwayland itself).

**Comment by curiositry** [comment]
Thanks for the reply and update @atx! I have reinstalled wtype with changes, but unfortunately it hasn't fixed the issue I'm having on Ubuntu 20.04 + Sway 1.4. 

It may not be relevant, but when I run wtype all keys and keystrokes stop working in Wayland windows *except* `esc`, which produces "0", `1`, which produces "-", and `2`, which produces "5" :/ (Caps lock also works, but I have it disabled with xkb, and the keycode remapped in my Sway config.) Keyboard input in Xwayland windows works fine.

Let me know if there’s any specific info that would be helpful for debugging...

**Comment by atx** [comment]
> It may not be relevant, but when I run wtype all keys and keystrokes stop working in Wayland windows except esc, which produces "0", 1, which produces "-", and 2, which produces "5"

Hm, this is really strange. It looks like wtype is somehow overriding the keymap for all your other inputs (note that esc, 1 and 2 have keycodes 9, 10 and 11 respectively, which are the first keycodes used by wtype). Do you have any specific input directives in your sway config file?

**Comment by curiositry** [comment]
Thank you @atk! This is very good news. I’ls hope this update trickles down into the Ubuntu sway package before too long. And if it doesn't, I'll switch to the master. 

Sorry for polluting your issue tracker with a Sway bug :)
