### ISSUE TITLE
wtype hangs on Sway 

### ISSUE THREAD

**Issue by curiositry** [atx/wtype#8]
I have built Sway v1.5-rc2 to get the fix for Issue #6, and built the latest version of wtype. However, when I run wtype (for example, `wtype ∇⋅∇ψ = ρ`), it hangs with no output or error message. (If I run it with no arguments, it behaves as expected: `Usage: wtype <text-to-type>`). Any idea what I might be doing wrong? Thanks!

(I'm a complete amateur when it comes to Wayland and C, so I'm probably just missing something obvious...)

**Comment by atx** [comment]
Should be fixed now (though my Wayland-fu is a bit rusty at the moment and I am not exactly sure why was it broken in the first place).

**Comment by curiositry** [comment]
Thanks @atx! It now works as intended with Sway on Ubuntu 20.04. (which means I can now use my "paste current date" keybinding on Wayland! :)
